-- Supabase SQL Editor-এ এই script চালাও।

create table if not exists public.clothes_votes (
  id bigint generated by default as identity primary key,
  option int not null check (option between 1 and 6),
  created_at timestamptz default now()
);

create table if not exists public.media (
  id uuid primary key default gen_random_uuid(),
  type text not null check (type in ('dhak','song','photo','greeting')),
  title text,
  caption text,
  url text,
  created_at timestamptz default now()
);

alter table public.clothes_votes enable row level security;
alter table public.media enable row level security;

-- Public visitors can see poll results and submit one vote from the site.
create policy "public can read votes"
on public.clothes_votes for select using (true);

create policy "public can vote"
on public.clothes_votes for insert with check (option between 1 and 6);

-- Public visitors can read uploaded media.
create policy "public can read media"
on public.media for select using (true);

-- Only logged-in admin accounts can manage media.
create policy "authenticated can insert media"
on public.media for insert to authenticated with check (true);

create policy "authenticated can delete media"
on public.media for delete to authenticated using (true);

-- Storage bucket.
insert into storage.buckets (id, name, public)
values ('media', 'media', true)
on conflict (id) do nothing;

create policy "public can view media files"
on storage.objects for select
using (bucket_id = 'media');

create policy "authenticated can upload media files"
on storage.objects for insert to authenticated
with check (bucket_id = 'media');

create policy "authenticated can delete media files"
on storage.objects for delete to authenticated
using (bucket_id = 'media');
